site_name: Readdocs-LLM_PARL
docs_dir:  docs
site_description: LLM-PARL
repo_url: https://github.com/Luffy521-art/Readdocs-LLM_PARL   # 替换为你的实际地址
repo_name: Readdocs-LLM_PARL

theme:
  name: material

nav:
  - 框架和算法公式: index.md
  - 20260909提速方案&显存压力&今日效果: 20260909提速方案&显存压力&今日效果.md
  - 20260910解决显存压力进度_day1: 20260910解决显存压力进度_day1.md
  - 20260911显存压力解决day2&&提速优化day1: 20260911显存压力解决day2&&提速优化day1.md
  - 20260912提速优化day2: 20260912提速优化day2.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
